<a href="https://colab.research.google.com/github/jasminef19/MyTelkomsel/blob/main/WEEK4/WEEK4_Regex_mytsel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Regular Expression#

2026/ PBA/ Irmasari Hafidz


Regex atau regular expressions, a.k.a. RE, re, regex, regexp, regex patterns.

Regex in Python docs dapat diakses di: https://docs.python.org/3/library/re.html

Pola dan strings yang bisa dicari:
*   Unicode strings (str)
*   8-bit strings (bytes)

Library yang dipakai adalah re

## Input dari .csv data scraping mytsel

In [16]:
import pandas as pd

# Define file path
file_path = "/content/df_mytselrev_50kNew.csv"

# Read the Excel file (only if the file exists)
df_mytselrev = pd.read_csv(file_path)

# Display the first few rows
df_mytselrev.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8013d176-fdf1-4fc6-9b23-cec2cd1c4754,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,banyak sekali bos,5,0,9.1.0,2026-03-04 15:42:04,NaN,NaN,9.1.0
1,1291c18e-5cb4-409b-bd82-e0a34c1aca98,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat bagus,5,0,9.1.0,2026-03-04 15:40:51,NaN,NaN,9.1.0
2,b88af38a-f45e-4436-908c-d1873c79e841,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,cerdas.cepat,5,0,9.1.0,2026-03-04 15:40:38,NaN,NaN,9.1.0
3,6987e130-a70d-495f-bc68-4d01945e14b0,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,jaringan gak stabil mending pake kartu lain aj...,1,0,6.12.2,2026-03-04 15:38:19,"Hai Kak Jax, Mohon maaf untuk ketidaknyamanann...",2026-03-04 16:08:26,6.12.2
4,7b084aa2-6a1b-4f21-baa6-ee5e80079c89,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Jelek sumpah jaringan tsel ini !! PARAH BANGET...,1,0,9.1.0,2026-03-04 15:37:11,"Hai Kak Resya, Mohon maaf untuk ketidaknyamana...",2026-03-04 16:24:17,9.1.0

In [27]:
df_mytselrev.columns

Index([' reviewId', 'userName', 'userImage', 'content', 'score',
       'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent',
       'repliedAt', 'appVersion', 'match_lemot'],
      dtype='object')

In [28]:
df_clean = df_mytselrev[[' reviewId', 'content']].copy()

#### teks merupakan paragraf2 yang diambil dari review aplikasi mytsel

In [29]:
import re

In [31]:
df_clean[df_clean['content'].str.contains(r'lemot', case=False, na=False)].head()

,reviewId,content
14,c745c55e-67f3-405c-bb8c-bd18419ec354,lemot susah di buka
18,3a5f5694-6021-487e-9670-41c807ec864f,sinyal terlalu lemot
21,6f9d2b7f-5e98-4f9e-a9a7-4c0c84cbe5ae,paketan makin mahal sinyal makin lemot
30,b2b4e5cc-2e75-4f5a-88fc-d08f161730a3,"Apk lemot, dan paket kok cuma 28 hari. beda de..."
31,fee3de24-fa69-43e6-ab1e-24330334a6eb,kecewa bgt dr th 2005 lancar dan enk sekarang ...

In [32]:
df_clean[
    df_clean['content'].str.contains(r'[Tt]idak *[Bb]isa', na=False)
].head()

,reviewId,content
76,acb0e705-9ad7-4f0b-876a-5a46aa2c3a0c,tidak bisa menghubungkan akun dengan gopay
128,ad2814ec-814f-4899-9943-7793e00ded86,ini jaringan Telkomsel Morowali sudah mau bang...
187,41cd4f1f-6499-40db-a51d-56757a17c6ee,we telkomsel.kenapa internet di pukul 18.00 sa...
233,b913fbc7-e160-45ea-b340-1837f935174b,Terpaksa saya turunkan Rating bintangnya!! Bik...
246,ba9ff128-ba07-42b3-a418-246d8018e011,"Aplikasi toIoI, mau transfer pulsa saja tidak ..."

In [38]:
all_text = "\n".join(df_clean['content'].astype(str))

pattern = r'.*[Tt]idak *[Bb]isa.*'
regex = re.compile(pattern)

results = regex.findall(all_text, re.MULTILINE)

results[:10]

['tidak bisa menghubungkan akun dengan gopay',
 'ini jaringan Telkomsel Morowali sudah mau bangkrut kh. ? jaringan sudah tidak bisa digunakan. layanan via aplikasi dan 188 tidak ada solusi penyelesaian. laporan dari Desember 2025. tidak di gubris sampai sekarang',
 'we telkomsel.kenapa internet di pukul 18.00 sampai pukul 23.00 tidak bisa di akses.semakin tidak jelas pelayanan anda ya.saya sebagai pelanggang merasa hak memakai internet di batasi selama 5 jam.',
 'Terpaksa saya turunkan Rating bintangnya!! Bikin Kecewa!! Ok, beli paket "Internet Sakti 21 GB" masa aktif 30 hari, tapi kenapa pada saat hari ke 28 sisa kuota untuk aplikasi YouTube, 4,1 GB lagi tidak bisa dipakai sama sekali.....?? jangan bo\'ongin customer dong yang jelas saja masa aktif 28 hari kan beres, jadi tak bikin bingung orang 😔😔👎🏼💔',
 'Aplikasi toIoI, mau transfer pulsa saja tidak bisa, anak haram csnya.',
 'Untuk registrasi setelah install harus klik tautan di sms yg dikirim telkomsel. Tapi tidak bisa di klik. Sudah dicoba berkali2 ...bagaimana mau masuk? ribet',
 'telkontol/Telkomsel adalah gsm paling mahal dan paling lelet internetnya, yang membuat jengkel itu lemah jaringan internetnya bahkan sampai tidak bisa di gunakan untuk apapun, mending cabut aja tower kalian biar gsm lain yg masuk kalian bukan jaringan yang bisa di gunakan, kalian gsm yg tidak lebih dari sekedar sampah dan lintah masyarakat, mahal jaringan lelet, kerja lambat, gsm laknat, BODOH.',
 'aplikasinya berat/lemot/lama buka,paket sedikit harga mahal,jaringan data buruk/jelek/lemot,belum lagi sinyal Telkomsel drop di hp saya/di tempat saya,pakai 5G drop,pakai 4G drop juga,akibatnya jaringan busuk,delay,lemot,dan baterai hp jadi cepat habis dan hp pun jadi cepat sekali panas,(makin tahun ke tahun berikutnya semakin buruk saja sinyal dan data jaringan Telkomsel),(kapan jaringan di indonesia stabil),rusak jaringan Telkomsel di jakarta timur,(tidak bisa di atasi jaringan Telkomsel).👎👎',
 'Susah x membuka aplikasi my telkomsel ini..sama sekali tidak bisa di buka Makin di update makin parah..n harga kuota sangat mahal, kuota sikit harga selangit..',
 'Kenapa Paket telkomsel sekarang masa aktifnya hanya 28 HARI??!!!!! SUDAH HARGA PAKET INTERNETNYA MAHAL dan kalau ada sisa kuota tidak bisa dikalkulasi atau dipakai lg dipaket berikutnya alias KUOTAnya HANGUS PULA!! TAMBAH MERUGIKAN PELANGGAN SAJA ya !!! DIPERHATIKANLAH HAK KONSUMEN !! EGOIS BANGET!! T4!k lah.']

In [39]:
pattern = r'(.*((T|t)idak *(B|b)isa).*)'
regex = re.compile(pattern)

results_group = regex.findall(all_text, re.MULTILINE)

results_group[:10]

[('tidak bisa menghubungkan akun dengan gopay', 'tidak bisa', 't', 'b'),
 ('ini jaringan Telkomsel Morowali sudah mau bangkrut kh. ? jaringan sudah tidak bisa digunakan. layanan via aplikasi dan 188 tidak ada solusi penyelesaian. laporan dari Desember 2025. tidak di gubris sampai sekarang',
  'tidak bisa',
  't',
  'b'),
 ('we telkomsel.kenapa internet di pukul 18.00 sampai pukul 23.00 tidak bisa di akses.semakin tidak jelas pelayanan anda ya.saya sebagai pelanggang merasa hak memakai internet di batasi selama 5 jam.',
  'tidak bisa',
  't',
  'b'),
 ('Terpaksa saya turunkan Rating bintangnya!! Bikin Kecewa!! Ok, beli paket "Internet Sakti 21 GB" masa aktif 30 hari, tapi kenapa pada saat hari ke 28 sisa kuota untuk aplikasi YouTube, 4,1 GB lagi tidak bisa dipakai sama sekali.....?? jangan bo\'ongin customer dong yang jelas saja masa aktif 28 hari kan beres, jadi tak bikin bingung orang 😔😔👎🏼💔',
  'tidak bisa',
  't',
  'b'),
 ('Aplikasi toIoI, mau transfer pulsa saja tidak bisa, anak haram csnya.',
  'tidak bisa',
  't',
  'b'),
 ('Untuk registrasi setelah install harus klik tautan di sms yg dikirim telkomsel. Tapi tidak bisa di klik. Sudah dicoba berkali2 ...bagaimana mau masuk? ribet',
  'tidak bisa',
  't',
  'b'),
 ('telkontol/Telkomsel adalah gsm paling mahal dan paling lelet internetnya, yang membuat jengkel itu lemah jaringan internetnya bahkan sampai tidak bisa di gunakan untuk apapun, mending cabut aja tower kalian biar gsm lain yg masuk kalian bukan jaringan yang bisa di gunakan, kalian gsm yg tidak lebih dari sekedar sampah dan lintah masyarakat, mahal jaringan lelet, kerja lambat, gsm laknat, BODOH.',
  'tidak bisa',
  't',
  'b'),
 ('aplikasinya berat/lemot/lama buka,paket sedikit harga mahal,jaringan data buruk/jelek/lemot,belum lagi sinyal Telkomsel drop di hp saya/di tempat saya,pakai 5G drop,pakai 4G drop juga,akibatnya jaringan busuk,delay,lemot,dan baterai hp jadi cepat habis dan hp pun jadi cepat sekali panas,(makin tahun ke tahun berikutnya semakin buruk saja sinyal dan data jaringan Telkomsel),(kapan jaringan di indonesia stabil),rusak jaringan Telkomsel di jakarta timur,(tidak bisa di atasi jaringan Telkomsel).👎👎',
  'tidak bisa',
  't',
  'b'),
 ('Susah x membuka aplikasi my telkomsel ini..sama sekali tidak bisa di buka Makin di update makin parah..n harga kuota sangat mahal, kuota sikit harga selangit..',
  'tidak bisa',
  't',
  'b'),
 ('Kenapa Paket telkomsel sekarang masa aktifnya hanya 28 HARI??!!!!! SUDAH HARGA PAKET INTERNETNYA MAHAL dan kalau ada sisa kuota tidak bisa dikalkulasi atau dipakai lg dipaket berikutnya alias KUOTAnya HANGUS PULA!! TAMBAH MERUGIKAN PELANGGAN SAJA ya !!! DIPERHATIKANLAH HAK KONSUMEN !! EGOIS BANGET!! T4!k lah.',
  'tidak bisa',
  't',
  'b')]

RE metacharacters that can be used in Python: (Ref: Justin Bois Regex's, lihat link Reference)

|     Metacharacter   |   Description   |
|:------------------:|-----------------|
| `.`                   | (dot) The ultimate wildcard. It matches any character other than the newline character (`\n`). If it is desireable to also match `\n` the alternative mode (`re.DOTALL`) can be invoked.
| `^`                   | (caret) Matches the start of a new string and the position immediately after a newline character.
| `$`                   | Similar to caret but goes for the end of the string and the character preceeding the newline character.
| `*`                   | The Kleene star  `*` following a RE allows 0 or multiple repitition of the this expression.  `ab*c` will match `ac`, `abc`, `abbc`, `abbbc`, ...
| `+`                   | Similar to the Kleene star, but it matches 1 or more occurences of the preceding RE, thus `ab+c` matches `abc`, `abbc`, `abbbc`, but not `ac`.
| `?`                   | Matches 0 or 1 repetition of the RE. `ab?` matches `a`, and `ab`.
| `{m}`                   | Matches exactly `m` repeats. `a{3}` equals `aaa`
| `{m,n}`                  | Matches m to n repeats, `a{2,4}` yields `aa`, `aaa`, and `aaaa`. The lower and upper bounds are optional `a{,4}` is the same as `a{0,4}`. Omiting the upper bound `a{4,}` yields anything with four or more repetitions of `a`.
| `[]`                   | Square brackets are used to describe a set of characters eg: `\[atcg\]` matches, `a`, `t`, `c`, or `g`, `\[a-z\]` matches any lowercase ASCII letter. `\[0-2\]\[0,9\]` matches all numbers from 00 to 29. It is important to note that metacharacters lose their special function within sets. Thus, `[(a\*b+)]` matches `(`, `a`, `\\`, `\*`, `b`, `+`, and `)`.
| `\\`                   | The escape character `\\` makes sure that the following character is interpreted literally. The Kleene star (`*`) for example will be interpreted as a simple asterisk if prefaced by the escape character (`\\\*`)
| &#124;                  | Logical or
| `(...)`                   | matches whatever regular expression is inside the parentheses.  As we discussed, these serve to describe groupings.

Reference


* Justin Bois i35 Regular Expression https://justinbois.github.io/bootcamp/2020/lessons/l35_regular_expressions.html
Colab pages at  https://colab.research.google.com/github/justinbois/bootcamp/blob/gh-pages/2021/lessons/l35_regular_expressions.ipynb#scrollTo=9ndPMg67CBES
*   https://web.mit.edu/hackl/www/lab/turkshop/slides/regex-cheatsheet.pdf

Menulis halaman ini (PBAWeek5_RegexPython.ipynb) dengan Markdown: https://colab.research.google.com/notebooks/markdown_guide.ipynb